### ISSUE TITLE
Use a table presentation library to better display the version check results

### ISSUE THREAD

**Issue by PaulDance** [PaulDance/cargo-liner#13]
It would be prettier while not too complicated. <https://github.com/zhiburt/tabled> is a good example. It should also help for #12.

**Comment by ToBinio** [comment]
I wanted to give this issue a shot since I wanted to play around with `tabled` for some time now.

and now have this

![image](https://github.com/PaulDance/cargo-liner/assets/81473300/ed612175-3a58-4595-ad53-33ecc783217a)

did you imagine the table to look like this?

note:
I added the current version to the ✔ because i think this information should be displayed somewhere

**Comment by PaulDance** [comment]
Hey, this is exactly what I had in mind, well done! If you open a PR with this, I would be happy to review it :slightly_smiling_face:

Note: you will have to update tests and example outputs. `TRYCMD=overwrite SNAPSHOTS=overwrite cargo test`, or something close since I'm only writing this from memory, should do the trick. When doing so, some parts may have to be manually updated in order to add the `[..]` and `...` matches back in order to obtain reproducible runs.
