### ISSUE TITLE
use cargo binstall if possible

### ISSUE THREAD

**Issue by ToBinio** [PaulDance/cargo-liner#16]
**Description**
The Rust compiler is very slow so compiling each package can take a very long time.

it would be nice if `cargo liner` uses `cargo binstall` if it's already installed.

**Additional context**
[cargo binstall](https://crates.io/crates/cargo-binstall)

note:
I would be able/interested in trying to implement this feature

**Comment by PaulDance** [comment]
Hi!

Thanks for the suggestion. This is indeed something I've had in mind for quite a bit as I see projects such as cargo-binstall or cargo-quickinstall often used in various places.

However, I currently see this as a more long-term sub-project, i.e. something with less priority than other things I want to implement first. It would indeed require a bit of integration work and managing optional dependencies is always a bit tricky. Furthermore, I would like to make it a proper functionality with both CLI and configuration having control over it, which takes a bit of design and implementation time.

If that's alright with you, I'll therefore let this open in the meantime to remind me of it, but not work on it quite yet. Of course, if you want it sooner, you can always take a crack at it, in which case I'll spend a bit of time for the design I would like and write some basic notes about it for you.

Cheers,
Paul.

**Comment by LucasFA** [comment]
I see it's already covered but:
>I would like to make it a proper functionality with both CLI and configuration having control over it

I agree - I'd like some way to keep the current behaviour and always compile it myself.

**Comment by PaulDance** [comment]
Yes, definitely. Remains the question of whether it should be enabled by default or not. Or make three possibilities available: an option to force the use of `cargo-binstall` or equivalent, an option for auto-detection and use (default), or a last one to disable anything related to this. Know that I also have the plan of exposing options in the configuration to set CLI controls to use by default, for example `liner.ship.no-self = true`, which could alleviate the burden of choosing the actual default now.

**Comment by seivan** [comment]
One way to breeze through it, would be if `cargo-binstall` is first in the list, install that and then default to it. 
If it's not ,then it's business as usual. 

I mean if someome has `cargo-binstall` installed, then the assumption is that it should be used. 
Also as far as I know, `cargo-binstall` itself will default to `cargo install` if prebuilts are not available.

**Comment by PaulDance** [comment]
> One way to breeze through it, would be if cargo-binstall is first in the list, install that and then default to it. If it's not ,then it's business as usual.

Yes, the auto check could indeed be done on each install so that a previous install of `cargo-binstall` during the global run could be taken into account.

> I mean if someome has cargo-binstall installed, then the assumption is that it should be used.

That is still the plan, yes.

> Also as far as I know, cargo-binstall itself will default to cargo install if prebuilts are not available.

I think that is done, yes. It does motivate an auto kind of behavior.

---

All of this would still have to be figured out precisely when implementing, though. I simply placed what could be of concern by thinking a bit in advance.

**Comment by PaulDance** [comment]
Hey all,

I went ahead and completed this in a way that I think should satisfy all mentioned use cases. The various choices and non-obvious aspects should be documented in the `README.md` and in the code. From my basic testing, it seems to behave like one would expect, I imagine.

I would be glad to receive your feedback regarding this. A working version should be available by building and installing Cargo Liner directly from this repository's `master` branch. Feel free to open new issues if somethings does not feel right, including bug reports even if they would concern a non-published version. In any case, I think I should be able to publish a version including this in the coming days, hopefully.

PS: sorry @ToBinio if I stepped on your toes somewhat while taking so long :disappointed: I initially thought it could have been a bit complex, so I postponed it by quite a bit and then preferred to hack at it myself in order to achieve the best I could design, while I think it was actually not that difficult in the end. Did you specifically want to implement this yourself, e.g. for the exercise, or did you only want the feature to land as soon as possible? If a similar situation should occur in the future, I'll definitely try to do better then :slightly_smiling_face:

**Comment by ToBinio** [comment]
All good, don't worry!
It's completely understandable that you want the best possible implementation, nice to see you still so passionate about this project!
Since I fully moved to Linux now, I don't really use cargo to manage any of my tools anymore 🙂

note: I quickly tested it, and it seems to work perfectly!
Thanks a lot!

**Comment by PaulDance** [comment]
Good, glad to hear!

**Comment by PaulDance** [comment]
This is now available as part of [v0.9.0](https://github.com/PaulDance/cargo-liner/releases/tag/v0.9.0).
