### ISSUE TITLE
Make CLI options of `ship` like `--no-fail-fast` available with the default command

### ISSUE THREAD

**Issue by halostatue** [PaulDance/cargo-liner#25]
**Description**

During a run of `cargo liner` (which is excellent and easier to use than `cargo-update`'s `cargo install-update`), I had a build fail and `cargo-liner` suggested using `--no-fail-fast`. This did not work:

```console
$ cargo liner --no-fail-fast
error: unexpected argument '--no-fail-fast' found

Usage: cargo liner [OPTIONS] [COMMAND]

For more information, try '--help'.
```

**Expected behavior**

Unknown arguments to be forwarded to the default command if none of the arguments are recognized.

**To Reproduce**

1. `cargo liner --no-fail-fast`
2. See error

**Context**
 - OS: macOS 14
 - Rust version: 1.83.0
 - Project version 0.8.0

**Comment by PaulDance** [comment]
Hey! Thanks for taking the time to report your issue.

> I had a build fail and `cargo-liner` suggested using `--no-fail-fast`. This did not work:

Yes, this is expected: the option applies only for the `ship` sub-command. As per [the documentation](https://github.com/PaulDance/cargo-liner#default-command):

> When the subcommand is omitted, it will use the `ship` subcommand with default options. See its specific documentation for more details.

So only a few global options are valid for both the default and the `ship` commands, and that was partly by design. In the meantime, you can always `cargo liner ship --no-fail-fast` or use the configuration's `defaults` if you want it to stay.

> Unknown arguments to be forwarded to the default command if none of the arguments are recognized.

I'll see what I can I do about this. However, as I use exclusively Clap for CLI arguments parsing and I would like that to stay, it might not be exactly possible. In any case, I'll refile this as a feature request if it's alright with you, since it was already expected behavior and adding what is wanted here is, well... adding 😉

Also, if I end up implementing this, I might only document it but not make the options' help sections be "upstreamed" to the default command in order to avoid polluting usage strings and the `README.md` with duplicates. However, depending on the feasibility of the addition, I might also decide not to move forward with this as I find the current situation should work well, although maybe not as intuitive as it could have been. We'll have to see, I guess 🙂

> which is excellent and easier to use than cargo-update's cargo install-update

❤️

**Comment by halostatue** [comment]
It didn't take me long to figure it out, but it was a point of confusion. I figured it was better to open an issue than not.

**Comment by PaulDance** [comment]
I looked into Clap a bit more and like I thought, I don't think there is a way to achieve this bubbling up of sorts cleanly. Indeed, the closest to it would be [`Arg::global`](https://docs.rs/clap/latest/clap/struct.Arg.html#method.global) that explicitly documents:

> Global arguments *only* propagate down, **not** up (to parent commands), however their values once a user uses them will be propagated back up to parents. In effect, this means one should *define* all global arguments at the top level, however it doesn’t matter where the user *uses* the global argument.

What would have been acceptable for me is for the `ship` options to silently bubble up to the default command. This way, the root command's usage documentation would not be cluttered up with duplicates and the `README.md` could help with this, although I think it would add confusion in order to fix confusion in the first place. However, this does not seem achievable, at least without hacks I don't really want to go into for something I think would be of a small gain. I will therefore avoid this particular aspect for now if that is alright with you.

I still pushed 69f6fcfd09e5a4e84f2ce2a08f921f8b21bc7822...e5fbb98fce9e7178d75f12d50f391aec7b87828f in order to compensate for this a bit: does that seem sufficient to you? This seemed like the only suggestion message I could find containing an option, so should be adequate in my opinion. I'll try to apply the same to any future similar case.

**Comment by halostatue** [comment]
Works for me.

**Comment by PaulDance** [comment]
Good!

**Comment by PaulDance** [comment]
Thanks for taking the time to report a point of confusion :+1:
